export const toolbarTitle = (() => {
    return {
        "undo": "撤销（⌘+Z）",
        "redo": "重做（⌘+Y）",
        "formatPaint": "格式刷，双击可重复使用",
        "clearFormat": "清除格式",
        "insert": "图标，表格等",
        "image": "图片",
        "table": "表格",
        "heading": "设置标题，可生成目录",
        "fontFamily": "字体",
        "fontSize": "字号码",
        "fontSizeIncrease": "增大字号（⌥ +.）",
        "fontSizeDecrease": "减小字号（⌥ +,）",
        "bold": "加粗（⌘+B）",
        "italic": "倾斜（⌘+I）",
        "underline": "下划线（⌘+U）",
        "strikeThrough": "删除线（⌘+⇧+X）",
        "sub": "下标（⌘+⇧+,）",
        "sup": "上标（⌘+⇧+.）",
        "letterSpacing": "字符间距",
        "fontBackgroundColor": "突出显示",
        "fontColor": "字体颜色",
        "bulletList": "项目符号（⌘+⇧+I）",
        "numberedList": "数字编号（⌘+⇧+U）",
        "taskList": "代办事项",
        "descIndent": "减少缩进（⌘+⇧+M）",
        "incIndent": "增加缩进（⌃+⇧+M）",
        "alignment": "对齐",
        "lineHeight": "行距",
        "quote": "引用",
        "lightBlock": "高亮块",
        "magic": "AI助手",
        "pageSettings": "页面设置",
        "addons": "扩展插件",
        "mention": "@人",
        "search": "查找和替换（⌘+F）",
    }
})()
